version: 2.1
jobs: # a collection of steps
  build: #title of 1rd section: runs not using Workflows must have a `build` job as entry point
    working_directory: ~/circleci-php # Here where the docker image and other files will be installed
    docker:
      - image: php:7.3-apache
        environment:
          APP_ENV: test
    steps: # list of commands 
      - checkout # special step to check out source code to working directory
      - run:
          name: Install unzip command to use sonarcloud/scan
          command: |
            apt-get update -y
            apt-get upgrade -y 
            apt-get install unzip
            apt install sudo
      - sonarcloud/scan
      - run:
          name: Install system packages
          command: apt-get -y install git
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo
      - run:
          name: installing Pcov as a debugger
          command: |
              pecl install pcov
              docker-php-ext-enable pcov
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: update project dependencies
          command: php composer.phar update
     #Test unit command
      - run:
          name: Run Unit tests
          command: php vendor\bin\phpunit --log-junit test-report.xml --coverage-clover coverage-report.xml --color
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud